title: ACNN Documentation

email: 
description: >-
  Documentation for the Attention Coupled Neural Network (ACNN) package.
baseurl: /notes.github.io
url: https://bonjour221.github.io
twitter_username: 
github_username: 
minimal_mistakes_skin: "air"
logo: "/assets/images/acnn-logo-hori.svg"
masthead_title: "ACNN Documentation"
locale: en-US
search: true
search_provider: lunr
search_full_content: true
lunr:
  search_within_pages: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# remote_theme: mmistakes/minimal-mistakes@gh-pages-3.1.6
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: 

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      lang: en
      base-url: "/"     
  - scope:
      path: zh
    values:
      lang: zh
      locale: zh-CN
      base-url: "/zh/"
